import os
import time
from typing import Tuple

import pandas as pd
from openai import OpenAI

from mcp_context import format_schema_context
from snowflake_client import run_query

# Blessed art though for thine free credits
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"), base_url="https://inference.baseten.co/v1")


def clean_sql_output(raw_output: str) -> str:
    """
    Cleans model output by stripping markdown formatting and extra text,
    returning only the SQL query.
    """
    # Remove code fences like ```sql ... ```
    if "```" in raw_output:
        raw_output = raw_output.split("```")[1]  # take the part inside fences
        # If model puts 'sql\n' after the fence, strip it
        raw_output = raw_output.lstrip("sql\n").strip()

    # Remove bold markers or other markdown artifacts
    raw_output = raw_output.replace("**", "").strip()

    return raw_output


def generate_sql(question: str, schema_context: dict) -> str:
    """
    Generates a SQL query for Snowflake from a natural language question.

    Args:
        question (str): Natural language question to convert into SQL.
        schema_context (dict): Dictionary mapping table names to lists of column names,
                               used to provide context to the LLM.

    Returns:
        str: SQL query generated by the LLM, cleaned of markdown artifacts.
    """
    schema_text = "\n".join([f"{t}: {cols}" for t, cols in schema_context.items()])
    prompt = f"""
    You are an assistant that generates SQL for Snowflake.
    Schema:
    {schema_text}

    Question: {question}

    Write a valid SQL query for Snowflake.
    """
    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=500,
        temperature=0,  # deterministic SQL
        top_p=1,
        presence_penalty=0,
        frequency_penalty=0,
    )

    raw_sql = response.choices[0].message.content.strip()
    sql = clean_sql_output(raw_sql)
    return sql


def run_query_with_retry(sql: str, retries=3, delay=1):
    for attempt in range(retries):
        try:
            return run_query(sql)
        except RuntimeError as e:
            print(f"Attempt {attempt+1} failed: {e}")
            time.sleep(delay)
    raise RuntimeError("All retries failed")


def ask(question: str) -> Tuple[str, pd.DataFrame]:
    """
    Executes the end-to-end process of generating SQL from a question
    and querying Snowflake.

    Args:
        question (str): Natural language question to query.

    Returns:
        str: Combined string containing the generated SQL and query results.
    """
    schema_context = format_schema_context()
    sql = generate_sql(question, schema_context)
    df = run_query_with_retry(sql)

    return sql, df


if __name__ == "__main__":
    sql, df = ask("Show me the top 5 customers by revenue")
    print("Generated SQL:\n", sql)
    if df is not None:
        print(df.head())
